# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(verbose_name='Account id')),
                ('account_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Bank Acount')),
                ('account_name', models.CharField(max_length=250, verbose_name='Account Name')),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Attendance Id')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('day', models.CharField(max_length=25, verbose_name='Day of the week')),
                ('attendance_status', models.CharField(choices=[('Present', 'Pesent'), ('Absent', 'Absent')], default='Absent', max_length=25, verbose_name='Attendance Status')),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Employee Id')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('mobile', models.IntegerField(verbose_name='Mobile')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('date_hired', models.DateField(verbose_name='Date hired')),
                ('year_experience', models.IntegerField(verbose_name='Year of experience')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7, verbose_name='Gender')),
                ('city', models.CharField(choices=[('BGR', 'Bangalore'), ('MBI', 'Mumbai'), ('DLI', 'Delhi'), ('DLI', 'LAGOS')], default='BGR', max_length=20, verbose_name='City')),
                ('country', models.CharField(choices=[('IND', 'India'), ('NGR', 'Nigeria'), ('GMB', 'Gambia')], default='IND', max_length=50, verbose_name='country')),
                ('employee_image', models.ImageField(upload_to='users/%Y/%M/%D/', verbose_name='Employee Image')),
                ('qualification', models.CharField(choices=[('Degree', 'Degree'), ('Master', 'Master'), ('Phd', 'Phd'), ('Other', 'Other')], default='Degree', max_length=50, verbose_name='Qualification')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='address')),
                ('employement_status', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Permanent', max_length=20, verbose_name='Employement Status')),
                ('skill_summary', models.TextField(verbose_name='Skill Summary')),
                ('account_number', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='hr.Account')),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hr.Department')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.IntegerField(primary_key=True, serialize=False)),
                ('allowances', models.FloatField(null=True, verbose_name='Allowances')),
                ('others', models.FloatField(null=True, verbose_name='Others')),
                ('loan', models.FloatField(null=True, verbose_name='Loan')),
                ('tax', models.FloatField(verbose_name='Tax')),
                ('account_number', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='hr.Account')),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hr.Department')),
                ('employee', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
            options={
                'db_table': 'Payroll',
            },
        ),
        migrations.CreateModel(
            name='Perfomance',
            fields=[
                ('perfomance_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Perfomance')),
                ('date_recorded', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('perfomance_rating', models.IntegerField(verbose_name='Rating /100')),
                ('remarks', models.TextField(verbose_name='remarks')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
            options={
                'db_table': 'Perfomance',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Project Id')),
                ('project_name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Department')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Salary Id')),
                ('salary', models.FloatField(verbose_name='Salary')),
            ],
            options={
                'db_table': 'Salary',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Training Id')),
                ('skill_report', models.TextField(verbose_name='Skill Report')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('remarks', models.TextField(verbose_name='Remarks')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Project')),
            ],
            options={
                'db_table': 'Training',
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.Salary'),
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Salary'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
        ),
    ]
