# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hr.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Salary'),
        ),
    ]
