# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20160930_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Leave id')),
                ('start_date', models.DateField(verbose_name='Leave Start Date')),
                ('end_date', models.DateField(verbose_name='Leave End Date')),
                ('reason', models.TextField(verbose_name='Reasons')),
                ('leave_status', models.CharField(max_length=250, verbose_name='Leave Status')),
                ('employee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
            options={
                'db_table': 'Leave',
            },
        ),
    ]
